version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.10.0
    branches:
      only:
        - master
        - develop
    working_directory: ~/text-and-people/frontend
    steps:
      - checkout
      - run:
          name: Install Dependencies...
          command: yarn install
